### ISSUE TITLE
can't populate Supabase using the SQL

### ISSUE THREAD

**Issue by j2l** [xulioc/sveltekit-supabase-dashboard#10]
Hello,
Great project!

Copy pasting https://github.com/xulioc/sveltekit-supabase-dashboard/blob/main/init_database.sql into supabase SQL Editor is not working for me.
First an error "near $", then "near select"
Any idea what I did wrong?

Have a great day!

**Comment by xulioc** [comment]
I think its an error because of the VSCODE formatter that changes $$ to $ $. I will try to fix later.

**Comment by j2l** [comment]
Thanks @xulioc, 
I also thought it and changed it, and I got other error like "near select".

**Comment by escopecz** [comment]
I'd love to give it a try as the demo link goes to itself. But I have similar issue. Error is very vague:

```
Error running SQL: Invalid SQL query
```
![Screenshot 2023-09-25 at 20 38 17](https://github.com/xulioc/sveltekit-supabase-dashboard/assets/1235442/554440fa-183b-4cd0-a92f-e87ec7e4d0dc)

Any clue how to debug this?

**Comment by j2l** [comment]
Nope, sorry. I started out from scratch in the end.

**Comment by escopecz** [comment]
Well, this was the first step so I'm not sure what starting from scratch means 😄
